#!/bin/sh
kpfolder="/usr/share/koolproxy/data"
kplogfile="/var/log/koolproxy.log"
readyfolder="/tmp/upload/koolproxy"

backup() {
	if [ ! -f $kpfolder/private/ca.key.pem ]; then
		echo "未找到ca.key.pem，请先运行KoolproxyM一次！" > $kplogfile
		exit 1
	fi
	if [ ! -f $kpfolder/private/base.key.pem ]; then
		echo "未找到base.key.pem，请先运行KoolproxyM一次！" > $kplogfile
		exit 1
	fi
	if [ ! -f $kpfolder/certs/ca.crt ]; then
		echo "未找到ca.crt，请先运行KoolproxyM一次！" > $kplogfile
		exit 1
	fi

	mkdir -p /tmp/upload
	cd $kpfolder
	tar czf /tmp/upload/koolproxyca.tar.gz private/ca.key.pem private/base.key.pem certs/ca.crt 
	[ -f /tmp/upload/koolproxyca.tar.gz ] && echo "证书备份已成功生成。" > $kplogfile 
}

kp_cert_0() {
	echo "开始生成  .0 证书！" > $kplogfile
	if [ ! -f /usr/share/koolproxy/data/certs/ca.crt ]; then
		echo "/usr/share/koolproxy/data/certs/ca.crt 不存在！"
	else
		ca_0_hash=$(openssl x509 -subject_hash_old -in /usr/share/koolproxy/data/certs/ca.crt|head -1).0
		cp /usr/share/koolproxy/data/certs/ca.crt /tmp/upload/$ca_0_hash
		openssl x509 -text -in cp /usr/share/koolproxy/data/certs/ca.crt -out /dev/null >> /tmp/upload/$ca_0_hash
		cd /tmp/upload
		tar czf ca_0.tar.gz $ca_0_hash
		rm -rf /tmp/upload/$ca_0_hash
	fi
}

restore() {
	if [ ! -f /tmp/upload/koolproxyCA.tar.gz ]; then
		echo "未找到备份文件，文件名必须为koolproxyCA.tar.gz或已损坏，请检查备份文件！" >> $kplogfile
	else
		mkdir -p $readyfolder
		cd $readyfolder
		tar xzf /tmp/upload/koolproxyCA.tar.gz
	fi
	if [ ! -f $readyfolder/private/ca.key.pem ]; then
		echo "未找到ca.key.pem,备份文件不正确或已损坏，请检查备份文件！" > $kplogfile
		exit 1
	fi
	if [ ! -f $readyfolder/private/base.key.pem ]; then
		echo "未找到base.key.pem，备份文件不正确或已损坏，请检查备份文件！" > $kplogfile
		exit 1
	fi
	if [ ! -f $readyfolder/certs/ca.crt ]; then
		echo "未找到ca.crt，备份文件不正确或已损坏，请检查备份文件！" > $kplogfile
		exit 1
	fi

	mv -f $readyfolder/private/ca.key.pem $kpfolder/private/ca.key.pem
	mv -f $readyfolder/private/base.key.pem $kpfolder/private/base.key.pem
	mv -f $readyfolder/certs/ca.crt $kpfolder/certs/ca.crt
	rm -rf $readyfolder
	rm -f /tmp/upload/koolproxyCA.tar.gz
	echo "证书成功还原，重启KoolproxyM。" > $kplogfile 
	/etc/init.d/koolproxy restart
}

case "$*" in
	"backup")
		backup
		;;
	"restore")
		restore
		;;
	"help")
		echo "use backup or restore"
		;;
	"kp_cert_0")
		kp_cert_0
		;;
esac
